spring.application.name=devops
server.port=8080
source.path=${SOURCE_PATH:./local}
environment=${APP_ENV:local}
build.number=${BUILD_NUMBER:local}
spring.thymeleaf.cache=false
spring.profiles.active=${APP_ENV:local}
spring.web.resources.add-mappings=false